<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'Save' => 'Сохранить',
	'Link' => 'Ссылка',
	'Pages to show banner' => 'Страницы на которых должен выводится баннер',
	'Settings' => 'Натройки',
	'Upload file' => 'Загрузка файла',
	'Apply' => 'Применить',
	'Status' => 'Статус',
	'Banners area' => 'Банерное место',
	'Updated At' => 'Дата последнего обновления',
	'Created At' => 'Дата создания',
	'Url' => 'Урл',
	'Show on internal pages' => 'Показывать на внутренних страницах',
	'Title' => 'Название',
	'width' => 'Ширина',
	'heigh' => 'Высота',
	'is_active' => 'Статус',
	'Yes' => 'Да',
	'No' => 'Нет',
	'Action' => 'Действие',
	'Views' => 'Показы',
	'Width' => 'Ширина',
	'Height' => 'Высоты',
	'Create Banner' => 'Создание банера',
	'Banners System' => 'Банерная система',
	'Active' => 'Активный',
	'Inactive' => 'Неактивный',
	'Update Banner' => 'Редактирование банера',
	'Are you sure you want to delete this item?' => 'Действительно хотете удалить?',
	'Update' => 'Редактировать',
	'Delete' => 'Удалить',
	'Banners' => 'Банеры',
	'Banner areas' => 'Банерные места',
	'Create' => 'Создать',
	'New banner' => 'Новый банер',
	'New area' => 'Новое банерное место',
	'Create banner area' => 'Создание банерного места',
	'Update banners area' => 'Редактирование банерного места',
	'Add new' => 'Добавить',
	'The archive is missing index.html' => 'В архиве отсутствует index.html',
	'Unable to unpack archive' => 'Невозможно распаковать архив',
	'Statistics' => 'Статистика',
	'Clicks' => 'Клики',
	'Type' => 'Способ вывода',
	'Rotate' => 'Поочередно',
	'List' => 'Списком',
];
